name: hive_demo_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.5
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  freezed_annotation: ^0.14.1

  # state management
  flutter_hooks: ^0.18.2
  hooks_riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  hive_generator: ^1.1.1
  json_serializable: ^5.0.2

flutter:
  uses-material-design: true
